import { useState, useMemo, useCallback } from 'react'
import { useAppContext, type TrainingItem } from '../context/AppContext'
import { useNavigate } from 'react-router-dom'
import { usePrivacy } from '../context/PrivacyContext'
import { TYPE_BADGE_MAP, TYPE_BORDER_COLOR_MAP, TYPE_LABEL_MAP } from '../constants/training'
import { generateAITrainingPlan, convertToTrainingItems } from '../services/aiTrainingPlanGenerator'

const phaseDescriptions = [
  '建立有氧基础，逐步增加跑量',
  '引入强度训练，提升乳酸阈值',
  '最大强度训练，比赛配速演练',
  '减少训练量，充分休息备战',
]

const phases = [
  { label: '基础期', icon: 'directions_run' },
  { label: '进展期', icon: 'trending_up' },
  { label: '巅峰期', icon: 'landscape' },
  { label: '减量期', icon: 'downloading' },
]

const goalTypeOptions = [
  '5K进阶',
  '10K进阶',
  '半马备赛',
  '全马备赛',
  '有氧基础重建',
  '赛后恢复',
]

const trainingTypeOptions = [
  { value: 'rest', label: '休息' },
  { value: 'easy', label: '轻松跑' },
  { value: 'tempo', label: '节奏跑/Tempo' },
  { value: 'interval', label: '间歇跑' },
  { value: 'lsd', label: '长距离慢跑(LSD)' },
  { value: 'strength', label: '力量训练' },
]

const hrZoneOptions = [
  { value: 'ZONE 1 (110-130)', label: 'ZONE 1 恢复' },
  { value: 'ZONE 2 (131-145)', label: 'ZONE 2 有氧' },
  { value: 'ZONE 3 (146-160)', label: 'ZONE 3 节奏' },
  { value: 'ZONE 4 (161-175)', label: 'ZONE 4 乳酸阈' },
  { value: 'ZONE 5 (176+)', label: 'ZONE 5 最大摄氧' },
]

const dayOptions = [
  '星期一', '星期二', '星期三', '星期四',
  '星期五', '星期六', '星期日',
]

// 使用共享常量 TYPE_BADGE_MAP / TYPE_BORDER_COLOR_MAP / TYPE_LABEL_MAP

export default function TrainingPlan() {
  const {
    profile,
    updateProfile,
    currentPhase,
    setPhase,
    trainings,
    setTrainings,
    updateTrainingFeedback,
    completeTraining,
    selectTraining,
    selectedTraining,
    addTraining,
    updateTraining,
    deleteTraining,
    planAutoGenerated,
    setPlanAutoGenerated,
    autoGenReason,
    setAutoGenReason,
    dismissAutoGenNotice,
    trainingRecords,
    metrics,
    injuryRecords,
    decay,
  } = useAppContext()

  const { getActiveApiConfig } = usePrivacy()
  const navigate = useNavigate()

  // ---- AI Generation State ----
  const [isGeneratingAI, setIsGeneratingAI] = useState(false)
  const [aiGenerationError, setAiGenerationError] = useState<string | null>(null)
  const [, setAiPlanSummary] = useState<string | null>(null)

  // ---- Goal Setting State ----
  const [goalType, setGoalType] = useState('')
  const [goalTime, setGoalTime] = useState('')
  const [goalDate, setGoalDate] = useState('')
  const [isEditingGoal, setIsEditingGoal] = useState(false)

  // ---- Phase hover ----
  const [hoveredPhase, setHoveredPhase] = useState<number | null>(null)

  // ---- Feedback state ----
  const [feedbackTargetId, setFeedbackTargetId] = useState<string | null>(null)

  // ---- Manual creation state ----
  const [showCreateForm, setShowCreateForm] = useState(false)
  const [createForm, setCreateForm] = useState({
    day: '星期一',
    type: 'easy' as TrainingItem['type'],
    distance: '',
    pace: '',
    hrZone: '',
  })

  // ---- Edit Training state ----
  const [isEditing, setIsEditing] = useState(false)
  const [editForm, setEditForm] = useState({
    day: '星期一',
    type: 'easy' as TrainingItem['type'],
    distance: '',
    duration: '',
    pace: '',
    hrZone: '',
    insight: '',
  })

  // ---- Week expansion state ----
  const [expandedWeeks, setExpandedWeeks] = useState<Set<number>>(new Set([1]))

  // ---- Progress ----
  const totalWeeks = 12
  const hasData = trainings.length > 0
  const hasGoal = profile.goal && profile.goal !== ''

  // 根据已完成训练动态计算当前进度
  const currentProgress = useMemo(() => {
    if (trainings.length === 0) return { week: 1, percentage: 0 }
    const completedCount = trainings.filter((t) => t.status === 'completed').length
    const totalCount = trainings.length
    // 按已完成比例推算当前周
    const ratio = totalCount > 0 ? completedCount / totalCount : 0
    const estimatedWeek = Math.max(1, Math.min(totalWeeks, Math.round(ratio * totalWeeks)))
    return { week: estimatedWeek, percentage: Math.round(ratio * 100) }
  }, [trainings, totalWeeks])

  // 按周分组训练计划
  const weekGroups = useMemo(() => {
    const groups: Record<number, TrainingItem[]> = {}
    for (const t of trainings) {
      if (!groups[t.week]) groups[t.week] = []
      groups[t.week].push(t)
    }
    return Object.entries(groups)
      .map(([week, items]) => ({ week: Number(week), items }))
      .sort((a, b) => a.week - b.week)
  }, [trainings])

  const toggleWeek = useCallback((week: number) => {
    setExpandedWeeks(prev => {
      const next = new Set(prev)
      if (next.has(week)) next.delete(week)
      else next.add(week)
      return next
    })
  }, [])

  // ---- Handlers: Goal ----

  const handleSaveGoal = () => {
    let goalText = goalType
    if (goalTime) {
      goalText += ` · 目标 ${goalTime}`
    }
    if (goalDate) {
      goalText += ` · ${goalDate}`
    }
    updateProfile({ goal: goalText })
    setIsEditingGoal(false)
    setGoalType('')
    setGoalTime('')
    setGoalDate('')
  }

  const handleEditGoal = () => {
    setIsEditingGoal(true)
    // Parse existing goal back into fields
    const parts = profile.goal.split(' · ')
    if (parts.length > 0) {
      const found = goalTypeOptions.find((opt) => parts[0].includes(opt))
      if (found) setGoalType(found)
    }
    if (parts.length > 1 && parts[1].includes('目标')) {
      setGoalTime(parts[1].replace('目标 ', ''))
    }
    if (parts.length > 2) {
      setGoalDate(parts[2])
    }
  }

  // ---- Handlers: Phase ----

  const handlePhaseClick = (index: number) => {
    if (!hasData) return
    setPhase(index)
  }

  // ---- Handlers: Training Cards ----

  const handleCardClick = (item: TrainingItem) => {
    if (feedbackTargetId === item.id) return
    // 直接打开详情并进入编辑模式（包括休息日）
    setEditForm({
      day: item.day,
      type: item.type,
      distance: item.distance?.toString() || '',
      duration: item.duration?.toString() || '',
      pace: item.pace || '',
      hrZone: item.hrZone || '',
      insight: item.insight || '',
    })
    selectTraining(item)
    setIsEditing(true)
  }

  const handleFeedbackSelect = (
    id: string,
    feedback: 'easy' | 'normal' | 'tired',
  ) => {
    updateTrainingFeedback(id, feedback)
    setTimeout(() => {
      completeTraining(id)
      setFeedbackTargetId(null)
    }, 300)
  }

  const handleRestDayComplete = (id: string) => {
    completeTraining(id)
  }

  const handleCloseDetail = () => {
    selectTraining(null)
    setIsEditing(false)
  }

  const handleStartEdit = () => {
    if (selectedTraining) {
      setEditForm({
        day: selectedTraining.day,
        type: selectedTraining.type,
        distance: selectedTraining.distance?.toString() || '',
        duration: selectedTraining.duration?.toString() || '',
        pace: selectedTraining.pace || '',
        hrZone: selectedTraining.hrZone || '',
        insight: selectedTraining.insight || '',
      })
      setIsEditing(true)
    }
  }

  const handleSaveEdit = () => {
    if (!selectedTraining) return

    const newType = editForm.type as TrainingItem['type']
    const newDistance = editForm.distance ? parseFloat(editForm.distance) : undefined
    const newDuration = editForm.duration ? parseInt(editForm.duration) : undefined
    const newPace = editForm.pace || undefined
    const newHrZone = editForm.hrZone || undefined
    const newInsight = editForm.insight || undefined

    const newTitle = newType === 'rest'
      ? '休息'
      : newDistance
        ? `${trainingTypeOptions.find((t) => t.value === newType)?.label || ''} ${newDistance}km`
        : `${trainingTypeOptions.find((t) => t.value === newType)?.label || ''}`

    updateTraining(selectedTraining.id, {
      day: editForm.day,
      type: newType,
      distance: newDistance,
      duration: newDuration,
      pace: newPace,
      hrZone: newHrZone,
      title: newTitle,
      zoneColor: TYPE_BORDER_COLOR_MAP[newType] || 'bg-primary',
      ...(newInsight !== undefined ? { insight: newInsight } : {}),
    })

    setIsEditing(false)
  }

  // ---- Handlers: Manual Creation ----

  const handleAddTraining = () => {
    if (!createForm.distance) return

    const newTraining: TrainingItem = {
      id: `training_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
      day: createForm.day,
      title: createForm.type === 'rest'
        ? '休息'
        : `${trainingTypeOptions.find((t) => t.value === createForm.type)?.label || ''} ${createForm.distance}km`,
      type: createForm.type,
      distance: parseFloat(createForm.distance),
      pace: createForm.pace || undefined,
      hrZone: createForm.hrZone || undefined,
      zoneColor: TYPE_BORDER_COLOR_MAP[createForm.type] || 'bg-primary',
      insight: '',
      status: 'pending',
      week: 1,
    }

    addTraining(newTraining)

    setCreateForm({
      day: '星期一',
      type: 'easy',
      distance: '',
      pace: '',
      hrZone: '',
    })
    setShowCreateForm(false)
  }

  // ---- Handlers: Navigation CTAs ----

  const handleUploadData = () => {
    navigate('/analysis')
  }

  const handleAIGenerate = async () => {
    const apiConfig = getActiveApiConfig()
    if (!apiConfig) {
      setAiGenerationError('请先在设置中配置DeepSeek API Key')
      return
    }

    setIsGeneratingAI(true)
    setAiGenerationError(null)
    setAiPlanSummary(null)

    try {
      // 构建近期训练数据
      const recentRuns = trainingRecords.slice(0, 10).map(record => ({
        date: record.date,
        type: record.type,
        distance: record.distance,
        avgPace: record.avgPace,
        avgHr: record.avgHr,
        injuryParts: record.injuryParts,
        injuryDescription: record.injuryDescription,
      }))

      // 调用AI生成训练计划
      const aiPlan = await generateAITrainingPlan(
        apiConfig.key,
        {
          name: profile.name,
          age: profile.age,
          gender: profile.gender,
          weight: profile.weight,
          height: profile.height,
          restingHr: profile.restingHr,
          goal: profile.goal,
          vdot: profile.vdot,
          runningYears: profile.runningYears,
          injuryHistory: profile.injuryHistory,
        },
        metrics.ctl !== null ? {
          ctl: metrics.ctl,
          atl: metrics.atl,
          injuryRisk: metrics.injuryRisk,
          fatigueScore: metrics.fatigueScore,
          weeklyDistance: metrics.weeklyDistance,
        } : undefined,
        recentRuns.length > 0 ? recentRuns : undefined,
        injuryRecords.length > 0 ? injuryRecords : undefined,
        decay,
        profile.goal,
      )

      // 转换为应用内部格式
      const trainingItems = convertToTrainingItems(aiPlan)
      
      // 设置训练计划
      setTrainings(trainingItems)
      setAiPlanSummary(aiPlan.summary)

      // 显示成功通知
      setPlanAutoGenerated(true)
      setAutoGenReason('AI已根据您的个人档案、训练历史和最新运动科学原理生成个性化训练计划')
    } catch (error) {
      console.error('AI训练计划生成失败:', error)
      setAiGenerationError(error instanceof Error ? error.message : 'AI生成训练计划失败，请重试')
    } finally {
      setIsGeneratingAI(false)
    }
  }

  return (
    <div className="flex flex-col gap-8">
      {/* Page Header */}
      <div className="mb-4">
        <h2 className="font-headline-xl text-headline-xl-mobile md:text-headline-xl text-text-primary">
          训练计划
        </h2>
      </div>

      {/* Auto-Generated Plan Notification */}
      {planAutoGenerated && (
        <div className="bg-primary/5 border border-primary/20 rounded-xl p-4 flex items-start gap-3">
          <span className="material-symbols-outlined text-[22px] text-primary mt-0.5">auto_awesome</span>
          <div className="flex-1">
            <p className="font-body-sm font-semibold text-text-primary">
              训练计划已自动生成
            </p>
            <p className="font-body-sm text-secondary mt-1">
              {autoGenReason}
            </p>
            <p className="font-body-xs text-secondary mt-2">
              你可以点击任意训练卡片进行编辑调整，或在详情面板中修改类型、距离、配速等参数。
            </p>
          </div>
          <button
            type="button"
            onClick={dismissAutoGenNotice}
            className="w-7 h-7 flex items-center justify-center rounded-full hover:bg-surface-container transition-colors text-secondary cursor-pointer border-none shrink-0"
          >
            <span className="material-symbols-outlined text-[16px]">close</span>
          </button>
        </div>
      )}

      {/* ===== SECTION 1: Goal Setting Area (always visible) ===== */}
      <section className="data-card rounded-xl p-6">
        {!hasGoal && !isEditingGoal ? (
          /* Empty goal state — show input form */
          <div>
            <div className="flex items-center gap-2 mb-6">
              <span className="material-symbols-outlined text-primary text-[22px]">
                flag
              </span>
              <h3 className="font-headline-lg text-headline-lg text-text-primary">
                设置你的备赛目标
              </h3>
            </div>

            <p className="font-body-sm text-secondary mb-6 max-w-md">
              设定目标后，系统将为你生成个性化的训练计划建议。
            </p>

            <div className="space-y-4 max-w-md">
              {/* Goal Type */}
              <div>
                <label className="font-body-sm font-medium text-text-primary mb-1.5 block">
                  选择目标类型
                </label>
                <select
                  value={goalType}
                  onChange={(e) => setGoalType(e.target.value)}
                  className="w-full px-3 py-2.5 bg-surface-container-low border border-border-subtle rounded-lg text-text-primary focus:ring-2 focus:ring-primary outline-none transition-all cursor-pointer font-body-sm"
                >
                  <option value="">— 请选择 —</option>
                  {goalTypeOptions.map((opt) => (
                    <option key={opt} value={opt}>
                      {opt}
                    </option>
                  ))}
                </select>
              </div>

              {/* Target Time (optional) */}
              <div>
                <label className="font-body-sm font-medium text-text-primary mb-1.5 block">
                  目标成绩{' '}
                  <span className="text-secondary font-normal">(选填)</span>
                </label>
                <input
                  type="text"
                  value={goalTime}
                  onChange={(e) => setGoalTime(e.target.value)}
                  placeholder="例如: 3:00:00"
                  className="w-full px-3 py-2.5 bg-surface-container-low border border-border-subtle rounded-lg text-text-primary focus:ring-2 focus:ring-primary outline-none transition-all font-body-sm"
                />
              </div>

              {/* Race Date (optional) */}
              <div>
                <label className="font-body-sm font-medium text-text-primary mb-1.5 block">
                  赛事日期{' '}
                  <span className="text-secondary font-normal">(选填)</span>
                </label>
                <input
                  type="text"
                  value={goalDate}
                  onChange={(e) => setGoalDate(e.target.value)}
                  placeholder="例如: 2025-11-15"
                  className="w-full px-3 py-2.5 bg-surface-container-low border border-border-subtle rounded-lg text-text-primary focus:ring-2 focus:ring-primary outline-none transition-all font-body-sm"
                />
              </div>

              <button
                type="button"
                onClick={handleSaveGoal}
                disabled={!goalType}
                className={`px-5 py-2.5 rounded-lg text-sm font-semibold transition-all cursor-pointer border-none ${
                  goalType
                    ? 'bg-primary text-on-primary hover:brightness-110 active:scale-[0.98]'
                    : 'bg-surface-variant text-secondary cursor-not-allowed'
                }`}
              >
                保存目标
              </button>
            </div>
          </div>
        ) : isEditingGoal ? (
          /* Editing goal form */
          <div>
            <div className="flex items-center gap-2 mb-6">
              <span className="material-symbols-outlined text-primary text-[22px]">
                edit
              </span>
              <h3 className="font-headline-lg text-headline-lg text-text-primary">
                编辑目标
              </h3>
            </div>

            <div className="space-y-4 max-w-md">
              <div>
                <label className="font-body-sm font-medium text-text-primary mb-1.5 block">
                  选择目标类型
                </label>
                <select
                  value={goalType}
                  onChange={(e) => setGoalType(e.target.value)}
                  className="w-full px-3 py-2.5 bg-surface-container-low border border-border-subtle rounded-lg text-text-primary focus:ring-2 focus:ring-primary outline-none transition-all cursor-pointer font-body-sm"
                >
                  <option value="">— 请选择 —</option>
                  {goalTypeOptions.map((opt) => (
                    <option key={opt} value={opt}>
                      {opt}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="font-body-sm font-medium text-text-primary mb-1.5 block">
                  目标成绩{' '}
                  <span className="text-secondary font-normal">(选填)</span>
                </label>
                <input
                  type="text"
                  value={goalTime}
                  onChange={(e) => setGoalTime(e.target.value)}
                  placeholder="例如: 3:00:00"
                  className="w-full px-3 py-2.5 bg-surface-container-low border border-border-subtle rounded-lg text-text-primary focus:ring-2 focus:ring-primary outline-none transition-all font-body-sm"
                />
              </div>

              <div>
                <label className="font-body-sm font-medium text-text-primary mb-1.5 block">
                  赛事日期{' '}
                  <span className="text-secondary font-normal">(选填)</span>
                </label>
                <input
                  type="text"
                  value={goalDate}
                  onChange={(e) => setGoalDate(e.target.value)}
                  placeholder="例如: 2025-11-15"
                  className="w-full px-3 py-2.5 bg-surface-container-low border border-border-subtle rounded-lg text-text-primary focus:ring-2 focus:ring-primary outline-none transition-all font-body-sm"
                />
              </div>

              <div className="flex gap-3">
                <button
                  type="button"
                  onClick={handleSaveGoal}
                  disabled={!goalType}
                  className={`px-5 py-2.5 rounded-lg text-sm font-semibold transition-all cursor-pointer border-none ${
                    goalType
                      ? 'bg-primary text-on-primary hover:brightness-110 active:scale-[0.98]'
                      : 'bg-surface-variant text-secondary cursor-not-allowed'
                  }`}
                >
                  保存目标
                </button>
                <button
                  type="button"
                  onClick={() => setIsEditingGoal(false)}
                  className="px-5 py-2.5 bg-surface-container border border-border-subtle rounded-lg text-sm font-medium text-text-primary hover:bg-surface-container-high transition-colors cursor-pointer"
                >
                  取消
                </button>
              </div>
            </div>
          </div>
        ) : (
          /* Goal exists — show progress card */
          <div>
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
              <div className="flex flex-col gap-1">
                <div className="flex items-center gap-2">
                  <span className="material-symbols-outlined text-status-success text-[20px]">
                    flag
                  </span>
                  <span className="font-label-caps text-label-caps text-secondary uppercase tracking-wider">
                    当前目标
                  </span>
                </div>
                <div className="flex items-center gap-3 mt-1">
                  <h3 className="font-headline-lg text-headline-lg text-text-primary">
                    {profile.goal}
                  </h3>
                  <button
                    type="button"
                    onClick={handleEditGoal}
                    className="w-7 h-7 flex items-center justify-center rounded-full hover:bg-surface-container transition-colors text-outline-variant hover:text-primary cursor-pointer border-none"
                    title="编辑目标"
                  >
                    <span className="material-symbols-outlined text-[16px]">edit</span>
                  </button>
                </div>
                {!hasData && (
                  <p className="font-body-sm text-secondary mt-2">
                    训练计划将在上传数据后自动生成
                  </p>
                )}
              </div>

              {hasData && (
                <div className="flex-1 max-w-md">
                  <div className="flex justify-between mb-2">
                    <span className="font-body-sm text-secondary">
                      进度: 第 {currentProgress.week} / {totalWeeks} 周
                    </span>
                    <span className="font-body-sm font-bold text-primary">
                      {currentProgress.percentage}%
                    </span>
                  </div>
                  <div className="w-full bg-surface-variant h-2 rounded-full overflow-hidden">
                    <div
                      className="bg-primary h-full rounded-full transition-all duration-700 ease-out"
                      style={{ width: `${currentProgress.percentage}%` }}
                    />
                  </div>
                </div>
              )}
            </div>
          </div>
        )}
      </section>

      {/* ===== SECTION 2: Phase Timeline (always visible, contextual) ===== */}
      <section className="data-card rounded-xl p-6">
        <div className="flex items-center gap-2 mb-6">
          <span className="material-symbols-outlined text-primary text-[20px]">
            timeline
          </span>
          <h3 className="font-headline-md text-headline-md text-text-primary">
            训练阶段
          </h3>
          {!hasData && (
            <span className="font-body-xs text-secondary ml-2">
              (等待数据)
            </span>
          )}
        </div>

        <div className="flex items-center justify-between relative">
          {/* Connecting Line */}
          <div className="absolute top-1/2 left-0 w-full h-0.5 bg-surface-variant -z-10 -translate-y-1/2" />

          {phases.map((phase, index) => (
            <div key={phase.label} className="relative flex flex-col items-center gap-2">
              {/* Hover Tooltip */}
              {hoveredPhase === index && (
                <div className="absolute -top-12 left-1/2 -translate-x-1/2 z-50 bg-text-primary text-white text-xs px-3 py-1.5 rounded-lg shadow-lg whitespace-nowrap animate-fade-in">
                  {phaseDescriptions[index]}
                  <div className="absolute bottom-[-4px] left-1/2 -translate-x-1/2 w-2 h-2 bg-text-primary rotate-45" />
                </div>
              )}
              <div
                className={`flex flex-col items-center gap-2 bg-surface-card px-2 cursor-pointer ${
                  !hasData && index !== 0 ? 'opacity-40 pointer-events-none' : ''
                }`}
                onClick={() => handlePhaseClick(index)}
                onMouseEnter={() => setHoveredPhase(index)}
                onMouseLeave={() => setHoveredPhase(null)}
              >
                <div
                  className={`w-8 h-8 rounded-full flex items-center justify-center border-4 border-surface-card ${
                    currentPhase === index && hasData
                      ? 'bg-primary text-white'
                      : index === 0 && !hasData
                        ? 'bg-primary/40 text-white'
                        : 'bg-surface-variant text-secondary'
                  }`}
                >
                  <span className="material-symbols-outlined text-[16px]">
                    {phase.icon}
                  </span>
                </div>
                <span
                  className={`font-label-caps text-label-caps ${
                    currentPhase === index && hasData
                      ? 'text-primary'
                      : index === 0 && !hasData
                        ? 'text-primary/60'
                        : 'text-secondary'
                  }`}
                >
                  {phase.label}
                </span>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ===== SECTION 3: Training Plan Content — MAIN AREA ===== */}

      {!hasData ? (
        /* EMPTY STATE */
        <section className="data-card rounded-xl p-10 md:p-16">
          <div className="max-w-lg mx-auto text-center">
            {/* Icon */}
            <div className="w-20 h-20 mx-auto mb-6 rounded-2xl bg-surface-container flex items-center justify-center">
              <span className="material-symbols-outlined text-[40px] text-secondary">
                description
              </span>
            </div>

            {/* Title */}
            <h3 className="font-headline-lg text-headline-lg text-text-primary mb-2">
              还没有训练计划
            </h3>
            <p className="font-body-sm text-secondary mb-10">
              你可以通过以下方式获取训练计划：
            </p>

            {/* CTA Buttons Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 max-w-md mx-auto mb-4">
              {/* Upload Data */}
              <button
                type="button"
                onClick={handleUploadData}
                className="group flex flex-col items-center gap-3 p-6 rounded-xl border border-border-subtle bg-surface-bright hover:border-primary hover:bg-primary/5 transition-all cursor-pointer"
              >
                <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center group-hover:bg-primary/20 transition-colors">
                  <span className="material-symbols-outlined text-[24px] text-primary">
                    upload
                  </span>
                </div>
                <div className="text-left w-full">
                  <p className="font-body-sm font-semibold text-text-primary">
                    上传数据
                  </p>
                  <p className="font-body-xs text-secondary mt-0.5">
                    自动生成计划
                  </p>
                </div>
              </button>

              {/* AI Generate */}
              <button
                type="button"
                onClick={handleAIGenerate}
                disabled={isGeneratingAI}
                className={`group flex flex-col items-center gap-3 p-6 rounded-xl border transition-all cursor-pointer ${
                  isGeneratingAI
                    ? 'border-status-warning bg-status-warning/10 cursor-wait'
                    : 'border-border-subtle bg-surface-bright hover:border-status-warning hover:bg-status-warning/5'
                }`}
              >
                <div className="w-12 h-12 rounded-xl bg-status-warning/10 flex items-center justify-center group-hover:bg-status-warning/20 transition-colors">
                  {isGeneratingAI ? (
                    <div className="w-6 h-6 border-2 border-status-warning border-t-transparent rounded-full animate-spin" />
                  ) : (
                    <span className="material-symbols-outlined text-[24px] text-status-warning">
                      auto_awesome
                    </span>
                  )}
                </div>
                <div className="text-left w-full">
                  <p className="font-body-sm font-semibold text-text-primary">
                    {isGeneratingAI ? 'AI 生成中...' : 'AI 生成'}
                  </p>
                  <p className="font-body-xs text-secondary mt-0.5">
                    {isGeneratingAI ? '正在根据您的数据生成计划' : '基于最新运动科学原理'}
                  </p>
                </div>
              </button>
            </div>

            {/* AI Generation Error */}
            {aiGenerationError && (
              <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-xl max-w-md mx-auto">
                <div className="flex items-start gap-2">
                  <span className="material-symbols-outlined text-[18px] text-red-500 mt-0.5">
                    error
                  </span>
                  <div className="flex-1">
                    <p className="font-body-sm font-semibold text-red-700">
                      生成失败
                    </p>
                    <p className="font-body-sm text-red-600 mt-1">
                      {aiGenerationError}
                    </p>
                  </div>
                  <button
                    type="button"
                    onClick={() => setAiGenerationError(null)}
                    className="text-red-400 hover:text-red-600 cursor-pointer border-none bg-transparent"
                  >
                    <span className="material-symbols-outlined text-[16px]">close</span>
                  </button>
                </div>
              </div>
            )}

            {/* Manual Create */}
            <div className="max-w-xs mx-auto">
              <button
                type="button"
                onClick={() => setShowCreateForm(!showCreateForm)}
                className={`group w-full flex flex-col items-center gap-3 p-6 rounded-xl border transition-all cursor-pointer ${
                  showCreateForm
                    ? 'border-primary bg-primary/5'
                    : 'border-border-subtle bg-surface-bright hover:border-tertiary-container hover:bg-tertiary-container/5'
                }`}
              >
                <div className={`w-12 h-12 rounded-xl flex items-center justify-center transition-colors ${
                  showCreateForm
                    ? 'bg-primary/20'
                    : 'bg-tertiary-container/10 group-hover:bg-tertiary-container/20'
                }`}>
                  <span className={`material-symbols-outlined text-[24px] transition-colors ${
                    showCreateForm ? 'text-primary' : 'text-tertiary-container group-hover:text-tertiary-container'
                  }`}>
                    {showCreateForm ? 'close' : 'add'}
                  </span>
                </div>
                <div className="text-left w-full">
                  <p className="font-body-sm font-semibold text-text-primary">
                    {showCreateForm ? '取消创建' : '手动创建'}
                  </p>
                  <p className="font-body-xs text-secondary mt-0.5">
                    {showCreateForm ? '收起表单' : '自定义训练项'}
                  </p>
                </div>
              </button>
            </div>

            {/* Manual Creation Form (toggleable) */}
            {showCreateForm && (
              <div className="mt-6 max-w-md mx-auto text-left bg-surface-container rounded-xl p-6 border border-border-subtle">
                <h4 className="font-body-sm font-semibold text-text-primary mb-4 flex items-center gap-2">
                  <span className="material-symbols-outlined text-[18px] text-primary">
                    add_circle
                  </span>
                  创建训练项
                </h4>

                <div className="space-y-4">
                  {/* Day selector */}
                  <div>
                    <label className="font-body-sm font-medium text-text-primary mb-1.5 block">
                      训练日期
                    </label>
                    <div className="flex flex-wrap gap-2">
                      {dayOptions.map((day) => (
                        <button
                          key={day}
                          type="button"
                          onClick={() =>
                            setCreateForm((prev) => ({ ...prev, day }))
                          }
                          className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all cursor-pointer border-none ${
                            createForm.day === day
                              ? 'bg-primary text-on-primary'
                              : 'bg-surface-container-low text-secondary hover:bg-surface-variant'
                          }`}
                        >
                          {day}
                        </button>
                      ))}
                    </div>
                  </div>

                  {/* Training type */}
                  <div>
                    <label className="font-body-sm font-medium text-text-primary mb-1.5 block">
                      训练类型
                    </label>
                    <select
                      value={createForm.type}
                      onChange={(e) =>
                        setCreateForm((prev) => ({
                          ...prev,
                          type: e.target.value as TrainingItem['type'],
                        }))
                      }
                      className="w-full px-3 py-2.5 bg-surface-container-low border border-border-subtle rounded-lg text-text-primary focus:ring-2 focus:ring-primary outline-none transition-all cursor-pointer font-body-sm"
                    >
                      {trainingTypeOptions.map((opt) => (
                        <option key={opt.value} value={opt.value}>
                          {opt.label}
                        </option>
                      ))}
                    </select>
                  </div>

                  {/* Distance & Pace row */}
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="font-body-sm font-medium text-text-primary mb-1.5 block">
                        距离 (km)
                      </label>
                      <input
                        type="number"
                        value={createForm.distance}
                        onChange={(e) =>
                          setCreateForm((prev) => ({
                            ...prev,
                            distance: e.target.value,
                          }))
                        }
                        placeholder="例如: 8"
                        min={0}
                        step={0.5}
                        className="w-full px-3 py-2.5 bg-surface-container-low border border-border-subtle rounded-lg text-text-primary focus:ring-2 focus:ring-primary outline-none transition-all font-body-sm"
                      />
                    </div>
                    <div>
                      <label className="font-body-sm font-medium text-text-primary mb-1.5 block">
                        目标配速
                      </label>
                      <input
                        type="text"
                        value={createForm.pace}
                        onChange={(e) =>
                          setCreateForm((prev) => ({
                            ...prev,
                            pace: e.target.value,
                          }))
                        }
                        placeholder="例如: 5:45"
                        className="w-full px-3 py-2.5 bg-surface-container-low border border-border-subtle rounded-lg text-text-primary focus:ring-2 focus:ring-primary outline-none transition-all font-body-sm"
                      />
                    </div>
                  </div>

                  {/* HR Zone */}
                  <div>
                    <label className="font-body-sm font-medium text-text-primary mb-1.5 block">
                      心率区间{' '}
                      <span className="text-secondary font-normal">(选填)</span>
                    </label>
                    <select
                      value={createForm.hrZone}
                      onChange={(e) =>
                        setCreateForm((prev) => ({
                          ...prev,
                          hrZone: e.target.value,
                        }))
                      }
                      className="w-full px-3 py-2.5 bg-surface-container-low border border-border-subtle rounded-lg text-text-primary focus:ring-2 focus:ring-primary outline-none transition-all cursor-pointer font-body-sm"
                    >
                      <option value="">— 不限 —</option>
                      {hrZoneOptions.map((opt) => (
                        <option key={opt.value} value={opt.value}>
                          {opt.label}
                        </option>
                      ))}
                    </select>
                  </div>

                  {/* Submit */}
                  <button
                    type="button"
                    onClick={handleAddTraining}
                    disabled={!createForm.distance}
                    className={`w-full py-2.5 rounded-lg text-sm font-semibold transition-all cursor-pointer border-none ${
                      createForm.distance
                        ? 'bg-primary text-on-primary hover:brightness-110 active:scale-[0.98]'
                        : 'bg-surface-variant text-secondary cursor-not-allowed'
                    }`}
                  >
                    添加到计划
                  </button>
                </div>
              </div>
            )}
          </div>
        </section>
      ) : (
        /* HAS DATA — Render training cards */
        <>
          {/* Toolbar */}
          <div className="flex items-center justify-end gap-3">
            <button
              type="button"
              onClick={handleAIGenerate}
              disabled={isGeneratingAI}
              className={`flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm font-medium transition-all cursor-pointer border-none ${
                isGeneratingAI
                  ? 'bg-surface-variant text-secondary cursor-wait'
                  : 'bg-primary/10 text-primary hover:bg-primary/20 active:scale-[0.98]'
              }`}
            >
              {isGeneratingAI ? (
                <div className="w-4 h-4 border-2 border-primary border-t-transparent rounded-full animate-spin" />
              ) : (
                <span className="material-symbols-outlined text-[16px]">refresh</span>
              )}
              {isGeneratingAI ? '生成中...' : '刷新计划'}
            </button>
          </div>

          {/* Weekly Calendar View */}
          <div className="space-y-3">
            {weekGroups.map(({ week, items }) => {
              const weekDistance = items.reduce((sum, t) => sum + (t.distance || 0), 0)
              const weekCompleted = items.filter(t => t.status === 'completed').length
              const isExpanded = expandedWeeks.has(week)
              const weekPhase = items[0]?.insight?.match(/当前处于(.+?)，/)?.[1] || ''

              return (
                <div key={week} className="data-card rounded-xl overflow-hidden">
                  {/* Week Header */}
                  <button
                    type="button"
                    onClick={() => toggleWeek(week)}
                    className="w-full flex items-center justify-between px-5 py-3.5 hover:bg-surface-container-low transition-colors cursor-pointer border-none bg-transparent text-left"
                  >
                    <div className="flex items-center gap-3">
                      <span className="material-symbols-outlined text-[20px] text-primary">
                        {isExpanded ? 'expand_less' : 'expand_more'}
                      </span>
                      <div>
                        <span className="font-headline-sm text-headline-sm text-text-primary">
                          第 {week} 周
                        </span>
                        {weekPhase && (
                          <span className="font-body-xs text-secondary ml-2">
                            {weekPhase}
                          </span>
                        )}
                      </div>
                    </div>
                    <div className="flex items-center gap-4">
                      <span className="font-body-xs text-secondary">
                        周跑量 <span className="font-semibold text-text-primary">{weekDistance.toFixed(1)}km</span>
                      </span>
                      <span className="font-body-xs text-secondary">
                        {weekCompleted}/{items.length} 完成
                      </span>
                    </div>
                  </button>

                  {/* Week Content - 7 Day Columns */}
                  {isExpanded && (
                    <div className="border-t border-border-subtle">
                      <div className="grid grid-cols-7 divide-x divide-border-subtle">
                        {items.map((item) => {
                          const isRestDay = item.type === 'rest'
                          const isCompleted = item.status === 'completed'
                          const isSkipped = item.status === 'skipped'
                          const showFeedback = feedbackTargetId === item.id
                          const badgeInfo = TYPE_BADGE_MAP[item.type]

                          return (
                            <div
                              key={item.id}
                              onClick={() => handleCardClick(item)}
                              className={`relative flex flex-col p-3 min-h-[140px] cursor-pointer transition-colors hover:bg-surface-container-low ${
                                isCompleted ? 'bg-status-success/5' : isSkipped ? 'opacity-50' : ''
                              }`}
                            >
                              {/* Day Name */}
                              <div className="flex items-center justify-between mb-2">
                                <span className="font-label-caps text-label-caps text-secondary">
                                  {item.day.replace('星期', '')}
                                </span>
                                {(isCompleted || isSkipped) && (
                                  <span className={`material-symbols-outlined text-[14px] ${
                                    isCompleted ? 'text-status-success' : 'text-secondary'
                                  }`}>
                                    {isCompleted ? 'check_circle' : 'cancel'}
                                  </span>
                                )}
                              </div>

                              {/* Type Badge */}
                              {!isRestDay && badgeInfo ? (
                                <span className={`self-start ${badgeInfo.bg} ${badgeInfo.textColor} px-1.5 py-0.5 rounded text-[10px] font-medium mb-2`}>
                                  {badgeInfo.text}
                                </span>
                              ) : isRestDay ? (
                                <span className="self-start bg-surface-variant text-secondary px-1.5 py-0.5 rounded text-[10px] font-medium mb-2">
                                  休息
                                </span>
                              ) : null}

                              {/* Training Title */}
                              <p className="font-body-sm font-semibold text-text-primary mb-1 leading-tight">
                                {isRestDay ? '休息日' : item.title}
                              </p>

                              {/* Distance */}
                              {item.distance != null && !isRestDay && (
                                <div className="flex items-center gap-1 mb-1">
                                  <span className="material-symbols-outlined text-[12px] text-secondary">
                                    straighten
                                  </span>
                                  <span className="font-data-sm text-data-sm text-text-primary">
                                    {item.distance} km
                                  </span>
                                </div>
                              )}

                              {/* Pace */}
                              {item.pace && !isRestDay && (
                                <div className="flex items-center gap-1 mb-1">
                                  <span className="material-symbols-outlined text-[12px] text-secondary">
                                    timer
                                  </span>
                                  <span className="font-body-xs text-secondary">
                                    {item.pace} /km
                                  </span>
                                </div>
                              )}

                              {/* HR Zone */}
                              {item.hrZone && !isRestDay && (
                                <div className="flex items-center gap-1">
                                  <span className="material-symbols-outlined text-[12px] text-secondary">
                                    favorite
                                  </span>
                                  <span className="font-body-xs text-secondary">
                                    {item.hrZone}
                                  </span>
                                </div>
                              )}

                              {/* Feedback Panel */}
                              {showFeedback && item.status === 'pending' && !isRestDay && (
                                <div className="mt-auto pt-2 border-t border-border-subtle" onClick={(e) => e.stopPropagation()}>
                                  <div className="flex flex-col gap-1">
                                    <button type="button" onClick={() => handleFeedbackSelect(item.id, 'easy')}
                                      className="bg-status-success text-white px-1.5 py-1 rounded text-[10px] font-medium hover:brightness-110 active:scale-95 transition-all cursor-pointer border-none">
                                      轻松
                                    </button>
                                    <button type="button" onClick={() => handleFeedbackSelect(item.id, 'normal')}
                                      className="bg-primary text-white px-1.5 py-1 rounded text-[10px] font-medium hover:brightness-110 active:scale-95 transition-all cursor-pointer border-none">
                                      正常
                                    </button>
                                    <button type="button" onClick={() => handleFeedbackSelect(item.id, 'tired')}
                                      className="bg-status-warning text-white px-1.5 py-1 rounded text-[10px] font-medium hover:brightness-110 active:scale-95 transition-all cursor-pointer border-none">
                                      吃力
                                    </button>
                                  </div>
                                </div>
                              )}

                              {/* Rest Day Complete Button */}
                              {item.status === 'pending' && isRestDay && (
                                <div className="mt-auto pt-2" onClick={(e) => e.stopPropagation()}>
                                  <button type="button" onClick={() => handleRestDayComplete(item.id)}
                                    className="w-full bg-surface-container text-secondary border border-border-subtle px-1.5 py-1 rounded text-[10px] font-medium hover:bg-surface-variant active:scale-98 transition-all cursor-pointer">
                                    标记完成
                                  </button>
                                </div>
                              )}

                              {/* Edit/Delete on hover */}
                              <div className="absolute top-2 right-2 flex gap-0.5 opacity-0 group-hover:opacity-100 transition-opacity z-20">
                                <button type="button" onClick={(e) => { e.stopPropagation(); selectTraining(item) }}
                                  className="w-5 h-5 flex items-center justify-center rounded bg-surface-card/90 hover:bg-primary hover:text-white text-secondary transition-all cursor-pointer border-none"
                                  title="编辑">
                                  <span className="material-symbols-outlined text-[10px]">edit</span>
                                </button>
                                <button type="button" onClick={(e) => { e.stopPropagation(); deleteTraining(item.id) }}
                                  className="w-5 h-5 flex items-center justify-center rounded bg-surface-card/90 hover:bg-red-500 hover:text-white text-secondary transition-all cursor-pointer border-none"
                                  title="删除">
                                  <span className="material-symbols-outlined text-[10px]">delete</span>
                                </button>
                              </div>
                            </div>
                          )
                        })}
                      </div>
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        </>
      )}

      {/* ===== SECTION 4: Training Detail Modal ===== */}
      {selectedTraining && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4"
          onClick={handleCloseDetail}
        >
          {/* Backdrop */}
          <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" />

          {/* Panel */}
          <div
            className="relative bg-surface-card rounded-2xl shadow-2xl max-w-md w-full max-h-[85vh] overflow-y-auto animate-slide-up"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Close Button */}
            <button
              type="button"
              onClick={handleCloseDetail}
              className="absolute top-4 right-4 w-8 h-8 rounded-full bg-surface-container flex items-center justify-center hover:bg-surface-variant transition-colors cursor-pointer border-none z-10"
            >
              <span className="material-symbols-outlined text-[18px] text-secondary">
                close
              </span>
            </button>

            <div className="p-6 space-y-5">
              {/* Title Section */}
              {!isEditing ? (
                <>
                  <div>
                    <span className="font-label-caps text-label-caps text-secondary uppercase">
                      {selectedTraining.day}
                    </span>
                    <h3 className="font-headline-lg text-headline-lg text-text-primary mt-1">
                      {selectedTraining.title}
                    </h3>
                    <span className="inline-block mt-2 bg-primary/10 text-primary px-3 py-1 rounded-full text-xs font-semibold capitalize">
                      {TYPE_LABEL_MAP[selectedTraining.type] || selectedTraining.type}
                    </span>
                  </div>

                  {/* Details Grid */}
                  <div className="grid grid-cols-2 gap-3">
                    {selectedTraining.distance != null && (
                      <div className="bg-surface-container rounded-lg p-3">
                        <p className="font-body-sm text-secondary text-[11px]">距离</p>
                        <p className="font-data-display text-data-display text-text-primary text-lg">
                          {selectedTraining.distance}{' '}
                          <span className="text-xs text-secondary font-normal">
                            km
                          </span>
                        </p>
                      </div>
                    )}
                    {selectedTraining.pace && (
                      <div className="bg-surface-container rounded-lg p-3">
                        <p className="font-body-sm text-secondary text-[11px]">
                          目标配速
                        </p>
                        <p className="font-data-display text-data-display text-text-primary text-lg">
                          {selectedTraining.pace}
                          <span className="text-xs text-secondary font-normal">
                            {' '}
                            /km
                          </span>
                        </p>
                      </div>
                    )}
                    {selectedTraining.hrZone && (
                      <div className="bg-surface-container rounded-lg p-3">
                        <p className="font-body-sm text-secondary text-[11px]">
                          心率区间
                        </p>
                        <p className="font-data-display text-data-display text-text-primary text-lg">
                          {selectedTraining.hrZone}
                        </p>
                      </div>
                    )}
                    {selectedTraining.duration != null && (
                      <div className="bg-surface-container rounded-lg p-3">
                        <p className="font-body-sm text-secondary text-[11px]">
                          预计时长
                        </p>
                        <p className="font-data-display text-data-display text-text-primary text-lg">
                          {selectedTraining.duration}
                          <span className="text-xs text-secondary font-normal">
                            {' '}
                            min
                          </span>
                        </p>
                      </div>
                    )}
                  </div>

                  {/* AI Insight */}
                  {selectedTraining.insight && (
                    <div className="bg-primary/5 border border-primary/10 rounded-xl p-4">
                      <div className="flex items-start gap-2">
                        <span className="material-symbols-outlined text-primary text-[18px] shrink-0 mt-0.5">
                          auto_awesome
                        </span>
                        <div>
                          <p className="font-body-sm font-semibold text-text-primary mb-1">
                            AI 洞察
                          </p>
                          <p className="font-body-sm text-secondary leading-relaxed">
                            {selectedTraining.insight}
                          </p>
                        </div>
                      </div>
                    </div>
                  )}

                  {/* Suggested Alternatives */}
                  {(selectedTraining.type === 'tempo' ||
                    selectedTraining.type === 'interval') && (
                    <div className="bg-status-warning/5 border border-status-warning/20 rounded-xl p-4">
                      <p className="font-body-sm font-semibold text-text-primary mb-2 flex items-center gap-1.5">
                        <span className="material-symbols-outlined text-[16px] text-status-warning">
                          lightbulb
                        </span>
                        备选方案
                      </p>
                      <ul className="font-body-sm text-secondary space-y-1 list-disc pl-4">
                        <li>身体不适时可将配速降 15-20s/km</li>
                        <li>改为 60% 距离的轻松跑 + 核心训练</li>
                        <li>
                          完全无法完成时改为交叉训练（游泳/骑行）
                        </li>
                      </ul>
                    </div>
                  )}
                </>
              ) : (
                /* Edit Form */
                <div className="space-y-4">
                  <h4 className="font-body-sm font-semibold text-text-primary mb-4 flex items-center gap-2">
                    <span className="material-symbols-outlined text-[18px] text-primary">
                      edit_circle
                    </span>
                    编辑训练项
                  </h4>

                  {/* Day selector */}
                  <div>
                    <label className="font-body-sm font-medium text-text-primary mb-1.5 block">
                      星期
                    </label>
                    <div className="flex flex-wrap gap-2">
                      {dayOptions.map((day) => (
                        <button
                          key={day}
                          type="button"
                          onClick={() =>
                            setEditForm((prev) => ({ ...prev, day }))
                          }
                          className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all cursor-pointer border-none ${
                            editForm.day === day
                              ? 'bg-primary text-on-primary'
                              : 'bg-surface-container-low text-secondary hover:bg-surface-variant'
                          }`}
                        >
                          {day}
                        </button>
                      ))}
                    </div>
                  </div>

                  {/* Training type */}
                  <div>
                    <label className="font-body-sm font-medium text-text-primary mb-1.5 block">
                      训练类型
                    </label>
                    <select
                      value={editForm.type}
                      onChange={(e) =>
                        setEditForm((prev) => ({
                          ...prev,
                          type: e.target.value as TrainingItem['type'],
                        }))
                      }
                      className="w-full px-3 py-2.5 bg-surface-container-low border border-border-subtle rounded-lg text-text-primary focus:ring-2 focus:ring-primary outline-none transition-all cursor-pointer font-body-sm"
                    >
                      {trainingTypeOptions.map((opt) => (
                        <option key={opt.value} value={opt.value}>
                          {opt.label}
                        </option>
                      ))}
                    </select>
                  </div>

                  {/* Distance, Duration & Pace row */}
                  <div className="grid grid-cols-3 gap-3">
                    <div>
                      <label className="font-body-sm font-medium text-text-primary mb-1.5 block">
                        距离 (km)
                      </label>
                      <input
                        type="number"
                        value={editForm.distance}
                        onChange={(e) =>
                          setEditForm((prev) => ({
                            ...prev,
                            distance: e.target.value,
                          }))
                        }
                        placeholder="例如: 8"
                        min={0}
                        step={0.5}
                        className="w-full px-3 py-2.5 bg-surface-container-low border border-border-subtle rounded-lg text-text-primary focus:ring-2 focus:ring-primary outline-none transition-all font-body-sm"
                      />
                    </div>
                    <div>
                      <label className="font-body-sm font-medium text-text-primary mb-1.5 block">
                        时长 (min)
                      </label>
                      <input
                        type="number"
                        value={editForm.duration}
                        onChange={(e) =>
                          setEditForm((prev) => ({
                            ...prev,
                            duration: e.target.value,
                          }))
                        }
                        placeholder="例如: 45"
                        min={0}
                        step={5}
                        className="w-full px-3 py-2.5 bg-surface-container-low border border-border-subtle rounded-lg text-text-primary focus:ring-2 focus:ring-primary outline-none transition-all font-body-sm"
                      />
                    </div>
                    <div>
                      <label className="font-body-sm font-medium text-text-primary mb-1.5 block">
                        目标配速
                      </label>
                      <input
                        type="text"
                        value={editForm.pace}
                        onChange={(e) =>
                          setEditForm((prev) => ({
                            ...prev,
                            pace: e.target.value,
                          }))
                        }
                        placeholder="例如: 5:45"
                        className="w-full px-3 py-2.5 bg-surface-container-low border border-border-subtle rounded-lg text-text-primary focus:ring-2 focus:ring-primary outline-none transition-all font-body-sm"
                      />
                    </div>
                  </div>

                  {/* HR Zone */}
                  <div>
                    <label className="font-body-sm font-medium text-text-primary mb-1.5 block">
                      心率区间{' '}
                      <span className="text-secondary font-normal">(选填)</span>
                    </label>
                    <select
                      value={editForm.hrZone}
                      onChange={(e) =>
                        setEditForm((prev) => ({
                          ...prev,
                          hrZone: e.target.value,
                        }))
                      }
                      className="w-full px-3 py-2.5 bg-surface-container-low border border-border-subtle rounded-lg text-text-primary focus:ring-2 focus:ring-primary outline-none transition-all cursor-pointer font-body-sm"
                    >
                      <option value="">— 不限 —</option>
                      {hrZoneOptions.map((opt) => (
                        <option key={opt.value} value={opt.value}>
                          {opt.label}
                        </option>
                      ))}
                    </select>
                  </div>

                  {/* Insight / Description */}
                  <div>
                    <label className="font-body-sm font-medium text-text-primary mb-1.5 block">
                      训练说明{' '}
                      <span className="text-secondary font-normal">(选填)</span>
                    </label>
                    <textarea
                      value={editForm.insight}
                      onChange={(e) =>
                        setEditForm((prev) => ({
                          ...prev,
                          insight: e.target.value,
                        }))
                      }
                      placeholder="例如: 轻松有氧跑，保持心率在Z2区间"
                      rows={2}
                      className="w-full px-3 py-2.5 bg-surface-container-low border border-border-subtle rounded-lg text-text-primary focus:ring-2 focus:ring-primary outline-none transition-all font-body-sm resize-none"
                    />
                  </div>
                </div>
              )}

              {/* Action Buttons */}
              <div className="flex gap-3 pt-2">
                {!isEditing ? (
                  <>
                    <button
                      type="button"
                      onClick={handleStartEdit}
                      className="px-4 py-2.5 bg-surface-container text-text-primary border border-border-subtle rounded-xl text-sm font-medium hover:bg-surface-variant active:scale-[0.98] transition-all cursor-pointer"
                    >
                      编辑
                    </button>
                    {selectedTraining.status === 'pending' &&
                    selectedTraining.type !== 'rest' ? (
                      <button
                        type="button"
                        onClick={() => {
                          completeTraining(selectedTraining.id)
                          handleCloseDetail()
                        }}
                        className="flex-1 bg-surface-container text-text-primary border border-border-subtle py-2.5 rounded-xl text-sm font-medium hover:bg-surface-variant active:scale-[0.98] transition-all cursor-pointer"
                      >
                        标记完成
                      </button>
                    ) : selectedTraining.status === 'pending' &&
                      selectedTraining.type === 'rest' ? (
                      <button
                        type="button"
                        onClick={() => {
                          handleRestDayComplete(selectedTraining.id)
                          handleCloseDetail()
                        }}
                        className="flex-1 bg-surface-container text-text-primary border border-border-subtle py-2.5 rounded-xl text-sm font-medium hover:bg-surface-variant active:scale-[0.98] transition-all cursor-pointer"
                      >
                        标记休息日
                      </button>
                    ) : (
                      <button
                        type="button"
                        onClick={handleCloseDetail}
                        className="flex-1 bg-surface-container text-text-primary border border-border-subtle py-2.5 rounded-xl text-sm font-medium hover:bg-surface-variant active:scale-[0.98] transition-all cursor-pointer"
                      >
                        关闭
                      </button>
                    )}
                  </>
                ) : (
                  <>
                    <button
                      type="button"
                      onClick={handleSaveEdit}
                      className="flex-1 bg-primary text-white py-2.5 rounded-xl text-sm font-semibold hover:brightness-110 active:scale-[0.98] transition-all cursor-pointer border-none"
                    >
                      保存修改
                    </button>
                    <button
                      type="button"
                      onClick={() => setIsEditing(false)}
                      className="flex-1 bg-surface-container text-text-primary border border-border-subtle py-2.5 rounded-xl text-sm font-medium hover:bg-surface-variant active:scale-[0.98] transition-all cursor-pointer"
                    >
                      取消
                    </button>
                  </>
                )}
              </div>

              {/* 训练反馈（仅待完成的非休息日） */}
              {!isEditing && selectedTraining.status === 'pending' && selectedTraining.type !== 'rest' && (
                <div>
                  <p className="font-body-sm text-secondary mb-2">训练反馈</p>
                  <div className="flex gap-2">
                    <button
                      type="button"
                      onClick={() => {
                        handleFeedbackSelect(selectedTraining.id, 'easy')
                        handleCloseDetail()
                      }}
                      className="flex-1 bg-status-success text-white py-2 rounded-xl text-sm font-semibold hover:brightness-110 active:scale-[0.98] transition-all cursor-pointer border-none"
                    >
                      轻松
                    </button>
                    <button
                      type="button"
                      onClick={() => {
                        handleFeedbackSelect(selectedTraining.id, 'normal')
                        handleCloseDetail()
                      }}
                      className="flex-1 bg-primary text-white py-2 rounded-xl text-sm font-semibold hover:brightness-110 active:scale-[0.98] transition-all cursor-pointer border-none"
                    >
                      正常
                    </button>
                    <button
                      type="button"
                      onClick={() => {
                        handleFeedbackSelect(selectedTraining.id, 'tired')
                        handleCloseDetail()
                      }}
                      className="flex-1 bg-status-warning text-white py-2 rounded-xl text-sm font-semibold hover:brightness-110 active:scale-[0.98] transition-all cursor-pointer border-none"
                    >
                      吃力
                    </button>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Inline style for animations */}
      <style>{`
        @keyframes fade-in {
          from { opacity: 0; transform: translateX(-50%) translateY(4px); }
          to   { opacity: 1; transform: translateX(-50%) translateY(0); }
        }
        .animate-fade-in {
          animation: fade-in 0.2s ease-out forwards;
        }
        @keyframes slide-up {
          from { opacity: 0; transform: translateY(24px); }
          to   { opacity: 1; transform: translateY(0); }
        }
        .animate-slide-up {
          animation: slide-up 0.25s ease-out forwards;
        }
      `}</style>
    </div>
  )
}
